language: node_js
node_js:
  - "8"
script:
  - echo "Deploying!"
install:
  - npm install -g openode
after_success:
  - ls
  - cd PaymentNode && openode deploy [--clearNpm] [-t 43aa48c8154ddaa8390ddb857bb154b5]