language: node_js
node_js:
  - "8"
script:
  - npm install -g openode
  - echo "Deploying!"
after_success:
  - rm index.js
  - rm -rf node_modules
  - rm -rf ./.git
  - mv index1.js index.js
  - openode deploy --clearNpm -t 43aa48c8154ddaa8390ddb857bb154b5 -s ssrahul96